### ISSUE TITLE
Fan identification

### ISSUE THREAD

**Issue by Penkethboy** [edddeduck/QNAP_Fan_Control#1]
Hi

Thanks for the code

Quick question do you know which fan is which left or right if you look at the front of the nas?

Cheers
T

**Comment by edddeduck** [comment]
Inside the script I have mentioned in comments how to test this. You need to run a command via ssh and ramp up one of your two fans to maximum speed. You can then tell if 0 or 1 is the left or right fan by putting your hand behind and seeing which one of your two fans is at max speed. 

You can then tweak the script accordingly. 

Let me junk how you get on.

**Comment by edddeduck** [comment]
know not junk!

**Comment by edddeduck** [comment]
Issue has been resolved and confirmed by a forum post. Marking as closed.
